server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/user_registration
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
          port: '587'
        transport:
          protocol: smtp
    host: smtp.gmail.com
    username: chiranw.15@itfac.mrt.ac.lk
    password: qmarpvwdgxyadrhv
